// Canonical nationwide senatorial district composition.
// District codes and names align with INEC constituency references.
// LGA memberships are normalized to nigeria_lga_catalog.dart slugs.
class SenatorialDistrictSeed {
  const SenatorialDistrictSeed({
    required this.code,
    required this.name,
    required this.stateId,
    required this.lgaSlugs,
  });

  final String code;
  final String name;
  final String stateId;
  final List<String> lgaSlugs;
}

const List<SenatorialDistrictSeed> nigeriaSenatorialDistricts = [
  SenatorialDistrictSeed(code: 'SD/001/AB', name: 'Abia North', stateId: 'AB', lgaSlugs: ['umu-nneochi', 'isuikwuato', 'ohafia', 'arochukwu', 'bende']),
  SenatorialDistrictSeed(code: 'SD/002/AB', name: 'Abia Central', stateId: 'AB', lgaSlugs: ['umuahia-north', 'umuahia-south', 'ikwuano', 'isiala-ngwa-north', 'isiala-ngwa-south']),
  SenatorialDistrictSeed(code: 'SD/003/AB', name: 'Abia South', stateId: 'AB', lgaSlugs: ['aba-north', 'aba-south', 'ugwunagbo', 'obingwa', 'ukwa-east', 'ukwa-west', 'osisioma']),
  SenatorialDistrictSeed(code: 'SD/004/AD', name: 'Adamawa North', stateId: 'AD', lgaSlugs: ['madagali', 'maiha', 'michika', 'mubi-north', 'mubi-south']),
  SenatorialDistrictSeed(code: 'SD/005/AD', name: 'Adamawa South', stateId: 'AD', lgaSlugs: ['demsa', 'ganye', 'guyuk', 'jada', 'mayo-belwa', 'numan', 'shelleng', 'toungo', 'lamurde']),
  SenatorialDistrictSeed(code: 'SD/006/AD', name: 'Adamawa Central', stateId: 'AD', lgaSlugs: ['hong', 'fufore', 'song', 'yola-north', 'yola-south', 'girei', 'gombi']),
  SenatorialDistrictSeed(code: 'SD/007/AK', name: 'Akwa Ibom North East', stateId: 'AK', lgaSlugs: ['etinan', 'ibesikpo-asutan', 'ibiono-ibom', 'itu', 'nsit-atai', 'nsit-ibom', 'nsit-ubium', 'uruan', 'uyo']),
  SenatorialDistrictSeed(code: 'SD/008/AK', name: 'Akwa Ibom North West', stateId: 'AK', lgaSlugs: ['abak', 'essien-udim', 'etim-ekpo', 'ika', 'ikono', 'ikot-ekpene', 'ini', 'obot-akara', 'oruk-anam', 'ukanafun']),
  SenatorialDistrictSeed(code: 'SD/009/AK', name: 'Akwa Ibom South', stateId: 'AK', lgaSlugs: ['eastern-obolo', 'eket', 'esit-eket', 'ibeno', 'ikot-abasi', 'mbo', 'mkpat-enin', 'okobo', 'onna', 'oron', 'udung-uko', 'urue-offong-oruko']),
  SenatorialDistrictSeed(code: 'SD/010/AN', name: 'Anambra North', stateId: 'AN', lgaSlugs: ['onitsha-north', 'onitsha-south', 'oyi', 'ogbaru', 'anambra-east', 'anambra-west', 'ayamelum']),
  SenatorialDistrictSeed(code: 'SD/011/AN', name: 'Anambra Central', stateId: 'AN', lgaSlugs: ['awka-north', 'awka-south', 'njikoka', 'anaocha', 'idemili-north', 'idemili-south', 'dunukofia']),
  SenatorialDistrictSeed(code: 'SD/012/AN', name: 'Anambra South', stateId: 'AN', lgaSlugs: ['ihiala', 'nnewi-north', 'nnewi-south', 'orumba-south', 'orumba-north', 'aguata', 'ekwusigo']),
  SenatorialDistrictSeed(code: 'SD/013/BA', name: 'Bauchi South', stateId: 'BA', lgaSlugs: ['alkaleri', 'kirfi', 'bauchi', 'tafawa-balewa', 'bogoro', 'dass', 'toro']),
  SenatorialDistrictSeed(code: 'SD/014/BA', name: 'Bauchi Central', stateId: 'BA', lgaSlugs: ['ningi', 'warji', 'darazo', 'ganjuwa', 'misau', 'dambam']),
  SenatorialDistrictSeed(code: 'SD/015/BA', name: 'Bauchi North', stateId: 'BA', lgaSlugs: ['zaki', 'gamawa', 'jama\'are', 'itas-gadau', 'shira', 'giade', 'katagum']),
  SenatorialDistrictSeed(code: 'SD/016/BY', name: 'Bayelsa East', stateId: 'BY', lgaSlugs: ['brass', 'nembe', 'ogbia']),
  SenatorialDistrictSeed(code: 'SD/017/BY', name: 'Bayelsa Central', stateId: 'BY', lgaSlugs: ['kolokuma-opokuma', 'southern-ijaw', 'yenagoa']),
  SenatorialDistrictSeed(code: 'SD/018/BY', name: 'Bayelsa West', stateId: 'BY', lgaSlugs: ['ekeremor', 'sagbama']),
  SenatorialDistrictSeed(code: 'SD/019/BN', name: 'Benue North East', stateId: 'BN', lgaSlugs: ['katsina-ala', 'konshisha', 'kwande', 'logo', 'ukum', 'ushongo', 'vandeikya']),
  SenatorialDistrictSeed(code: 'SD/020/BN', name: 'Benue North West', stateId: 'BN', lgaSlugs: ['buruku', 'gboko', 'guma', 'gwer-east', 'gwer-west', 'makurdi', 'tarka']),
  SenatorialDistrictSeed(code: 'SD/021/BN', name: 'Benue South', stateId: 'BN', lgaSlugs: ['ado', 'agatu', 'apa', 'obi', 'ogbadibo', 'ohimini', 'oju', 'okpokwu', 'otukpo']),
  SenatorialDistrictSeed(code: 'SD/022/BO', name: 'Borno North', stateId: 'BO', lgaSlugs: ['abadam', 'gubio', 'guzamala', 'kukawa', 'magumeri', 'marte', 'mobbar', 'nganzai', 'monguno']),
  SenatorialDistrictSeed(code: 'SD/023/BO', name: 'Borno Central', stateId: 'BO', lgaSlugs: ['dikwa', 'jere', 'kala-balge', 'mafa', 'maiduguri', 'ngala', 'konduga', 'bama', 'kaga']),
  SenatorialDistrictSeed(code: 'SD/024/BO', name: 'Borno South', stateId: 'BO', lgaSlugs: ['askira-uba', 'bayo', 'biu', 'chibok', 'damboa', 'gwoza', 'hawul', 'kwaya-kusar', 'shani']),
  SenatorialDistrictSeed(code: 'SD/025/CR', name: 'Cross River North', stateId: 'CR', lgaSlugs: ['bekwarra', 'obanliku', 'obudu', 'ogoja', 'yala']),
  SenatorialDistrictSeed(code: 'SD/026/CR', name: 'Cross River Central', stateId: 'CR', lgaSlugs: ['abi', 'boki', 'etung', 'ikom', 'obubra', 'yakurr']),
  SenatorialDistrictSeed(code: 'SD/027/CR', name: 'Cross River South', stateId: 'CR', lgaSlugs: ['calabar-municipality', 'calabar-south', 'akamkpa', 'akpabuyo', 'bakassi', 'biase', 'odukpani']),
  SenatorialDistrictSeed(code: 'SD/028/DT', name: 'Delta Central', stateId: 'DE', lgaSlugs: ['ethiope-east', 'ethiope-west', 'okpe', 'sapele', 'udu', 'ughelli-north', 'ughelli-south', 'uvwie']),
  SenatorialDistrictSeed(code: 'SD/029/DT', name: 'Delta North', stateId: 'DE', lgaSlugs: ['aniocha-north', 'aniocha-south', 'ika-north-east', 'ika-south', 'ndokwa-east', 'ndokwa-west', 'oshimili-north', 'oshimili-south', 'ukwuani']),
  SenatorialDistrictSeed(code: 'SD/030/DT', name: 'Delta South', stateId: 'DE', lgaSlugs: ['bomadi', 'burutu', 'isoko-north', 'isoko-south', 'patani', 'warri-north', 'warri-south', 'warri-south-west']),
  SenatorialDistrictSeed(code: 'SD/031/EB', name: 'Ebonyi North', stateId: 'EB', lgaSlugs: ['abakaliki', 'ebonyi', 'izzi', 'ohaukwu']),
  SenatorialDistrictSeed(code: 'SD/032/EB', name: 'Ebonyi Central', stateId: 'EB', lgaSlugs: ['ezza-north', 'ezza-south', 'ikwo', 'ishielu']),
  SenatorialDistrictSeed(code: 'SD/033/EB', name: 'Ebonyi South', stateId: 'EB', lgaSlugs: ['afikpo-north', 'afikpo-south', 'ivo', 'ohaozara', 'onicha']),
  SenatorialDistrictSeed(code: 'SD/034/ED', name: 'Edo Central', stateId: 'ED', lgaSlugs: ['esan-central', 'esan-north-east', 'esan-south-east', 'esan-west', 'igueben']),
  SenatorialDistrictSeed(code: 'SD/035/ED', name: 'Edo North', stateId: 'ED', lgaSlugs: ['akoko-edo', 'etsako-east', 'etsako-central', 'etsako-west', 'owan-east', 'owan-west']),
  SenatorialDistrictSeed(code: 'SD/036/ED', name: 'Edo South', stateId: 'ED', lgaSlugs: ['oredo', 'orhionmwon', 'ovia-north-east', 'ovia-south-west', 'egor', 'uhunmwode', 'ikpoba-okha']),
  SenatorialDistrictSeed(code: 'SD/037/EK', name: 'Ekiti North', stateId: 'EK', lgaSlugs: ['ikole', 'oye', 'ido-osi', 'moba', 'ilejemeje']),
  SenatorialDistrictSeed(code: 'SD/038/EK', name: 'Ekiti Central', stateId: 'EK', lgaSlugs: ['ado-ekiti', 'irepodun-ifelodun', 'ijero', 'efon', 'ekiti-west']),
  SenatorialDistrictSeed(code: 'SD/039/EK', name: 'Ekiti South', stateId: 'EK', lgaSlugs: ['ekiti-south-west', 'ikere', 'emure', 'ise-orun', 'gbonyin', 'ekiti-east']),
  SenatorialDistrictSeed(code: 'SD/040/EN', name: 'Enugu East', stateId: 'EN', lgaSlugs: ['enugu-east', 'enugu-north', 'enugu-south', 'isi-uzo', 'nkanu-east', 'nkanu-west']),
  SenatorialDistrictSeed(code: 'SD/041/EN', name: 'Enugu West', stateId: 'EN', lgaSlugs: ['aninri', 'awgu', 'ezeagu', 'oji-river', 'udi']),
  SenatorialDistrictSeed(code: 'SD/042/EN', name: 'Enugu North', stateId: 'EN', lgaSlugs: ['igbo-etiti', 'igbo-eze-north', 'igbo-eze-south', 'uzo-uwani', 'udenu', 'nsukka']),
  SenatorialDistrictSeed(code: 'SD/043/GM', name: 'Gombe Central', stateId: 'GO', lgaSlugs: ['akko', 'yalmaltu-deba']),
  SenatorialDistrictSeed(code: 'SD/044/GM', name: 'Gombe South', stateId: 'GO', lgaSlugs: ['balanga', 'billiri', 'kaltungo', 'shongom']),
  SenatorialDistrictSeed(code: 'SD/045/GM', name: 'Gombe North', stateId: 'GO', lgaSlugs: ['funakaye', 'nafada', 'gombe', 'kwami', 'dukku']),
  SenatorialDistrictSeed(code: 'SD/046/IM', name: 'Imo East', stateId: 'IM', lgaSlugs: ['aboh-mbaise', 'ahiazu-mbaise', 'ezinihitte-mbaise', 'ikeduru', 'mbaitoli', 'ngor-okpala', 'owerri-urban', 'owerri-north', 'owerri-west']),
  SenatorialDistrictSeed(code: 'SD/047/IM', name: 'Imo West', stateId: 'IM', lgaSlugs: ['ideato-north', 'ideato-south', 'isu', 'njaba', 'nkwerre', 'nwangele', 'oguta', 'ohaji-egbema', 'orlu', 'orsu', 'oru-west', 'oru-east']),
  SenatorialDistrictSeed(code: 'SD/048/IM', name: 'Imo North', stateId: 'IM', lgaSlugs: ['ehime-mbano', 'ihitte-uboma', 'isiala-mbano', 'obowo', 'okigwe', 'onuimo']),
  SenatorialDistrictSeed(code: 'SD/049/JG', name: 'Jigawa South West', stateId: 'JI', lgaSlugs: ['birnin-kudu', 'buji', 'dutse', 'gwaram', 'kiyawa', 'jahun', 'miga']),
  SenatorialDistrictSeed(code: 'SD/050/JG', name: 'Jigawa North East', stateId: 'JI', lgaSlugs: ['auyo', 'birniwa', 'guri', 'hadejia', 'kaugama', 'kafin-hausa', 'kirika-samma', 'malam-madori']),
  SenatorialDistrictSeed(code: 'SD/051/JG', name: 'Jigawa North West', stateId: 'JI', lgaSlugs: ['babura', 'gagarawa', 'garki', 'gwiwa', 'kazaure', 'maigatari', 'roni', 'ringim', 'sule-tankarkar', 'taura', 'yankwashi', 'gumel']),
  SenatorialDistrictSeed(code: 'SD/052/KD', name: 'Kaduna North', stateId: 'KD', lgaSlugs: ['kubau', 'ikara', 'makarfi', 'soba', 'sabon-gari', 'zaria', 'lere', 'kudan']),
  SenatorialDistrictSeed(code: 'SD/053/KD', name: 'Kaduna Central', stateId: 'KD', lgaSlugs: ['birnin-gwari', 'giwa', 'igabi', 'kaduna-north', 'kaduna-south', 'chikun', 'kajuru']),
  SenatorialDistrictSeed(code: 'SD/054/KD', name: 'Kaduna South', stateId: 'KD', lgaSlugs: ['jema\'a', 'jaba', 'kaura', 'zangon-kataf', 'kauru', 'kachia', 'kagarko', 'sanga']),
  SenatorialDistrictSeed(code: 'SD/055/KN', name: 'Kano Central', stateId: 'KN', lgaSlugs: ['dala', 'gwale', 'dawaki-kudu', 'gezawa', 'tarauni', 'fagge', 'garun-malam', 'kano-municipal', 'kumbotso', 'kura', 'madobi', 'minjibir', 'nasarawa', 'ungogo', 'warawa']),
  SenatorialDistrictSeed(code: 'SD/056/KN', name: 'Kano North', stateId: 'KN', lgaSlugs: ['bichi', 'shanono', 'bagwai', 'danbata', 'makoda', 'dawaki-tofa', 'gabasawa', 'gwarzo', 'kabo', 'rimin-gado', 'tofa', 'tsanyawa', 'kunchi', 'karaye']),
  SenatorialDistrictSeed(code: 'SD/057/KN', name: 'Kano South', stateId: 'KN', lgaSlugs: ['albasu', 'bebeji', 'bunkure', 'doguwa', 'gaya', 'kiru', 'rano', 'takai', 'ajingi', 'rogo', 'kibiya', 'tudun-wada', 'garko', 'wudil', 'sumaila']),
  SenatorialDistrictSeed(code: 'SD/058/KT', name: 'Katsina North', stateId: 'KT', lgaSlugs: ['daura', 'zango', 'mai\'adua', 'mashi', 'mani', 'ingawa', 'bindawa', 'sandamu', 'dutsi', 'kankia', 'kusada', 'baure']),
  SenatorialDistrictSeed(code: 'SD/059/KT', name: 'Katsina South', stateId: 'KT', lgaSlugs: ['funtua', 'faskari', 'danja', 'dandume', 'bakori', 'kankara', 'malumfashi', 'kafur', 'musawa', 'matazu', 'sabuwa']),
  SenatorialDistrictSeed(code: 'SD/060/KT', name: 'Katsina Central', stateId: 'KT', lgaSlugs: ['katsina', 'kaita', 'jibia', 'batsari', 'safana', 'dutsin-ma', 'kurfi', 'batagarawa', 'rimi', 'charanchi', 'dan-musa']),
  SenatorialDistrictSeed(code: 'SD/061/KB', name: 'Kebbi North', stateId: 'KE', lgaSlugs: ['arewa', 'argungu', 'augie', 'bagudo', 'dandi', 'suru', 'jega']),
  SenatorialDistrictSeed(code: 'SD/062/KB', name: 'Kebbi Central', stateId: 'KE', lgaSlugs: ['aliero', 'birnin-kebbi', 'bunza', 'gwandu', 'kalgo', 'koko-besse', 'maiyama']),
  SenatorialDistrictSeed(code: 'SD/063/KB', name: 'Kebbi South', stateId: 'KE', lgaSlugs: ['fakai', 'ngaski', 'sakaba', 'shanga', 'wasagu-danko', 'yauri', 'zuru']),
  SenatorialDistrictSeed(code: 'SD/064/KG', name: 'Kogi Central', stateId: 'KO', lgaSlugs: ['adavi', 'ajaokuta', 'ogori-magongo', 'okehi', 'okene']),
  SenatorialDistrictSeed(code: 'SD/065/KG', name: 'Kogi East', stateId: 'KO', lgaSlugs: ['ankpa', 'bassa', 'dekina', 'ibaji', 'idah', 'igalamela-odolu', 'ofu', 'olamaboro', 'omala']),
  SenatorialDistrictSeed(code: 'SD/066/KG', name: 'Kogi West', stateId: 'KO', lgaSlugs: ['ijumu', 'kabba-bunu', 'koton-karfe', 'lokoja', 'mopa-muro', 'yagba-east', 'yagba-west']),
  SenatorialDistrictSeed(code: 'SD/067/KW', name: 'Kwara North', stateId: 'KW', lgaSlugs: ['baruten', 'edu', 'patigi', 'kaiama', 'moro']),
  SenatorialDistrictSeed(code: 'SD/068/KW', name: 'Kwara Central', stateId: 'KW', lgaSlugs: ['asa', 'ilorin-east', 'ilorin-south', 'ilorin-west', 'offa']),
  SenatorialDistrictSeed(code: 'SD/069/KW', name: 'Kwara South', stateId: 'KW', lgaSlugs: ['ekiti', 'oke-ero', 'ifelodun', 'irepodun', 'isin', 'oyun']),
  SenatorialDistrictSeed(code: 'SD/070/LA', name: 'Lagos Central', stateId: 'LA', lgaSlugs: ['lagos-island', 'lagos-mainland', 'surulere', 'apapa', 'eti-osa']),
  SenatorialDistrictSeed(code: 'SD/071/LA', name: 'Lagos East', stateId: 'LA', lgaSlugs: ['somolu', 'kosofe', 'epe', 'ibeju-lekki', 'ikorodu']),
  SenatorialDistrictSeed(code: 'SD/072/LA', name: 'Lagos West', stateId: 'LA', lgaSlugs: ['agege', 'ifako-ijaye', 'alimosho', 'badagry', 'ojo', 'ajeromi-ifelodun', 'amuwo-odofin', 'oshodi-isolo', 'ikeja', 'mushin']),
  SenatorialDistrictSeed(code: 'SD/073/NW', name: 'Nasarawa North', stateId: 'NA', lgaSlugs: ['akwanga', 'nasarawa-eggon', 'wamba']),
  SenatorialDistrictSeed(code: 'SD/074/NW', name: 'Nasarawa West', stateId: 'NA', lgaSlugs: ['nasarawa', 'keffi', 'kokona', 'karu', 'toto']),
  SenatorialDistrictSeed(code: 'SD/075/NW', name: 'Nasarawa South', stateId: 'NA', lgaSlugs: ['lafia', 'awe', 'doma', 'keana', 'obi']),
  SenatorialDistrictSeed(code: 'SD/076/NG', name: 'Niger East', stateId: 'NI', lgaSlugs: ['bosso', 'chanchaga', 'gurara', 'paikoro', 'rafi', 'shiroro', 'munya', 'suleja', 'tafa']),
  SenatorialDistrictSeed(code: 'SD/077/NG', name: 'Niger North', stateId: 'NI', lgaSlugs: ['agwara', 'borgu', 'kontagora', 'mariga', 'rijau', 'wushishi', 'mashegu', 'magama']),
  SenatorialDistrictSeed(code: 'SD/078/NG', name: 'Niger South', stateId: 'NI', lgaSlugs: ['agaie', 'bida', 'katcha', 'gbako', 'lapai', 'lavun', 'edatti', 'mokwa']),
  SenatorialDistrictSeed(code: 'SD/079/OG', name: 'Ogun Central', stateId: 'OG', lgaSlugs: ['ifo', 'ewekoro', 'obafemi-owode', 'abeokuta-north', 'abeokuta-south', 'odeda']),
  SenatorialDistrictSeed(code: 'SD/080/OG', name: 'Ogun East', stateId: 'OG', lgaSlugs: ['sagamu', 'ikenne', 'remo-north', 'ijebu-ode', 'odogbolu', 'ijebu-north-east', 'ijebu-north', 'ijebu-east', 'ogun-water-side']),
  SenatorialDistrictSeed(code: 'SD/081/OG', name: 'Ogun West', stateId: 'OG', lgaSlugs: ['imeko-afon', 'yewa-egbado-north', 'yewa-egbado-south', 'ipokia', 'ado-odo-ota']),
  SenatorialDistrictSeed(code: 'SD/082/OD', name: 'Ondo North', stateId: 'ON', lgaSlugs: ['akoko-north-east', 'akoko-north-west', 'akoko-south-west', 'akoko-south-east', 'ose', 'owo']),
  SenatorialDistrictSeed(code: 'SD/083/OD', name: 'Ondo Central', stateId: 'ON', lgaSlugs: ['akure-north', 'akure-south', 'ifedore', 'idanre', 'ondo-east', 'ondo-west']),
  SenatorialDistrictSeed(code: 'SD/084/OD', name: 'Ondo South', stateId: 'ON', lgaSlugs: ['ileoluji-okeigbo', 'odigbo', 'irele', 'okitipupa', 'ese-odo', 'ilaje']),
  SenatorialDistrictSeed(code: 'SD/085/OS', name: 'Osun Central', stateId: 'OS', lgaSlugs: ['boripe', 'boluwaduro', 'ifelodun', 'ila', 'ifedayo', 'irepodun', 'orolu', 'odo-otin', 'olorunda', 'osogbo']),
  SenatorialDistrictSeed(code: 'SD/086/OS', name: 'Osun East', stateId: 'OS', lgaSlugs: ['atakumosa-east', 'atakumosa-west', 'ife-central', 'ife-east', 'ife-north', 'ife-south', 'ilesa-east', 'ilesa-west', 'obokun', 'oriade']),
  SenatorialDistrictSeed(code: 'SD/087/OS', name: 'Osun West', stateId: 'OS', lgaSlugs: ['ayedaade', 'ayedire', 'ede-north', 'ede-south', 'egbedore', 'ejigbo', 'irewole', 'isokan', 'iwo', 'ola-oluwa']),
  SenatorialDistrictSeed(code: 'SD/088/OY', name: 'Oyo Central', stateId: 'OY', lgaSlugs: ['afijio', 'akinyele', 'egbeda', 'ogo-oluwa', 'surulere', 'lagelu', 'oluyole', 'ona-ara', 'oyo-east', 'oyo-west', 'atiba']),
  SenatorialDistrictSeed(code: 'SD/089/OY', name: 'Oyo North', stateId: 'OY', lgaSlugs: ['saki-west', 'saki-east', 'atisbo', 'irepo', 'olorunsogo', 'kajola', 'iwajowa', 'ogbomoso-north', 'ogbomoso-south', 'iseyin', 'orelope', 'ori-ire', 'itesiwaju']),
  SenatorialDistrictSeed(code: 'SD/090/OY', name: 'Oyo South', stateId: 'OY', lgaSlugs: ['ibadan-north', 'ibadan-north-east', 'ibadan-north-west', 'ibadan-south-east', 'ibadan-south-west', 'ibarapa-central', 'ibarapa-north', 'ibarapa-east', 'ido']),
  SenatorialDistrictSeed(code: 'SD/091/PL', name: 'Plateau South', stateId: 'PL', lgaSlugs: ['langtang-north', 'langtang-south', 'mikang', 'qua\'an-pan', 'shendam', 'wase']),
  SenatorialDistrictSeed(code: 'SD/092/PL', name: 'Plateau Central', stateId: 'PL', lgaSlugs: ['bokkos', 'kanke', 'mangu', 'pankshin', 'kanam']),
  SenatorialDistrictSeed(code: 'SD/093/PL', name: 'Plateau North', stateId: 'PL', lgaSlugs: ['barikin-ladi', 'bassa', 'jos-east', 'jos-north', 'jos-south', 'riyom']),
  SenatorialDistrictSeed(code: 'SD/094/RV', name: 'Rivers East', stateId: 'RI', lgaSlugs: ['etche', 'omuma', 'ikwerre', 'obio-akpor', 'port-harcourt', 'okrika', 'ogu-bolo', 'emohua']),
  SenatorialDistrictSeed(code: 'SD/095/RV', name: 'Rivers South East', stateId: 'RI', lgaSlugs: ['opobo-nkoro', 'andoni', 'oyigbo', 'tai', 'eleme', 'gokana', 'khana']),
  SenatorialDistrictSeed(code: 'SD/096/RV', name: 'Rivers West', stateId: 'RI', lgaSlugs: ['asari-toru', 'akuku-toru', 'degema', 'ogba-egbema-ndoni', 'abua-odual', 'ahoada-east', 'ahoada-west', 'bonny']),
  SenatorialDistrictSeed(code: 'SD/097/SO', name: 'Sokoto East', stateId: 'SO', lgaSlugs: ['isa', 'sabon-birni', 'wurno', 'goronyo', 'rabah', 'gada', 'illela', 'gwadabawa']),
  SenatorialDistrictSeed(code: 'SD/098/SO', name: 'Sokoto North', stateId: 'SO', lgaSlugs: ['tangaza', 'binji', 'silame', 'gudu', 'kware', 'wamakko', 'sokoto-north', 'sokoto-south']),
  SenatorialDistrictSeed(code: 'SD/099/SO', name: 'Sokoto South', stateId: 'SO', lgaSlugs: ['dange-shuni', 'tureta', 'bodinga', 'shagari', 'yabo', 'tambuwal', 'kebbe']),
  SenatorialDistrictSeed(code: 'SD/100/TR', name: 'Taraba South', stateId: 'TA', lgaSlugs: ['wukari', 'ibi', 'donga', 'ussa', 'takum']),
  SenatorialDistrictSeed(code: 'SD/101/TR', name: 'Taraba Central', stateId: 'TA', lgaSlugs: ['sardauna', 'kurmi', 'bali', 'gashaka', 'gassol']),
  SenatorialDistrictSeed(code: 'SD/102/TR', name: 'Taraba North', stateId: 'TA', lgaSlugs: ['jalingo', 'yorro', 'zing', 'lau', 'ardo-kola', 'karim-lamido']),
  SenatorialDistrictSeed(code: 'SD/103/YB', name: 'Yobe East', stateId: 'YO', lgaSlugs: ['bursari', 'geidam', 'gujba', 'gulani', 'tarmuwa', 'yunusari']),
  SenatorialDistrictSeed(code: 'SD/104/YB', name: 'Yobe North', stateId: 'YO', lgaSlugs: ['bade', 'jakusko', 'machina', 'karasuwa', 'nguru', 'yusufari']),
  SenatorialDistrictSeed(code: 'SD/105/YB', name: 'Yobe South', stateId: 'YO', lgaSlugs: ['fika', 'fune', 'nangere', 'potiskum', 'damaturu']),
  SenatorialDistrictSeed(code: 'SD/106/ZF', name: 'Zamfara North', stateId: 'ZA', lgaSlugs: ['kaura-namoda', 'shinkafi', 'zurmi', 'birnin-magaji']),
  SenatorialDistrictSeed(code: 'SD/107/ZF', name: 'Zamfara Central', stateId: 'ZA', lgaSlugs: ['gusau', 'tsafe', 'bungudu', 'maru']),
  SenatorialDistrictSeed(code: 'SD/108/ZF', name: 'Zamfara West', stateId: 'ZA', lgaSlugs: ['maradun', 'bakura', 'anka', 'bukkuyum', 'gummi', 'talata-mafara']),
  SenatorialDistrictSeed(code: 'SD/109/FCT', name: 'Federal Capital Territory', stateId: 'FCT', lgaSlugs: ['abaji', 'gwagwalada', 'kuje', 'abuja-municipal', 'kwali', 'bwari']),
];
